export { default as Dashboard } from './Dashboard';
export { default as Login } from './Login';
export { default as SplashScreen } from './SplashScreen';
export { default as Today } from './Today';
export { default as Calendar } from './Calendar';
export { default as Schedule } from './Schedule';
export { default as Subject } from './Schedule/Subject';
export { default as SubChapters } from './Schedule/Subject/Syllabus/SubChapters';
export { default as Profile } from './Profile';
